### ISSUE TITLE
"It seems to be possible to avoid the \oplus_{i=1}^{n_i}" (in Breen-Deligne)?

### ISSUE THREAD

**Issue by kbuzzard** [leanprover-community/liquid#1]
What is going on here? Is the claim that the statement of Breen-Deligne can be strengthened to furthermore assume n_i = 1 for all i, or is the claim not this? If the claim is this then why doesn't Breen-Deligne/Scholze say this, and if the claim is not this then are we digging ourselves into a hole by not setting up the theory in the correct generality?

**Comment by PeterScholze** [comment]
Well, we do say that, in the appendix to Lecture 9!

**Comment by kbuzzard** [comment]
OK great :-) I'm just reading the blueprint through from the start and this jumped out at me.
