### ISSUE TITLE
Definition of homotopy in Def 1.8

### ISSUE THREAD

**Issue by kbuzzard** [leanprover-community/liquid#2]
The way this is set up right now, there is no "h_{-1}", the zero map, and no claim that f_0 \circ h_0 = sigma_alpha - sigma_pi as universal maps from exponent 2n_0 to n_0 (the case "i=-1"). Is this correct? Note that in the example of Definition 1.10 this extra equation holds.

**Comment by jcommelin** [comment]
Yes, this condition should be added. It is present in the Lean code already.

**Comment by kbuzzard** [comment]
I'll add it in a commit to the "fixes" branch which I'm making right now.
