### ISSUE TITLE
morphism of profinitely filtered pseudo-normed groups

### ISSUE THREAD

**Issue by kbuzzard** [leanprover-community/liquid#3]
Definition 2.1: a morphism has to be bounded (there exists C such that...; note that if one C exists then any C' >= C will also work) and continuous -- but which C' does one choose? I'd like to say "for one C (or equivalently for all C), the induced map is continuous", so let's check this. Inclusions are continuous so making C bigger isn't a problem. To check that making C smaller isn't a problem one needs to check that if X -> Y -> Z are maps between profinite sets and Y -> Z is a continuous inclusion and the composite X -> Z is continuous, then X -> Y is continuous. This should be OK because the topology on Y must be the one induced from the inclusion, by general properties of inclusions between compact Hausdorff spaces, right? I am modifying the definition to make this point clearer in the `fixes` branch and I just wanted to run the argument past someone -- if a passing mathematician believes me then feel free to close this issue :-)

**Comment by jcommelin** [comment]
Here is the formal def'n:
```lean
structure profinitely_filtered_pseudo_normed_group_hom (M₁ M₂ : Type*)
  [profinitely_filtered_pseudo_normed_group M₁]
  [profinitely_filtered_pseudo_normed_group M₂]
  extends M₁ →+ M₂ :=
(bound' : ∃ C, ∀ c x, x ∈ filtration M₁ c → to_fun x ∈ filtration M₂ (C * c))
(continuous' : ∀ ⦃c₁ c₂⦄ (f₀ : filtration M₁ c₁ → filtration M₂ c₂)
  (h : ∀ x, to_fun ↑x = f₀ x), continuous f₀)
```
So we ask that for any function $$f_0 : M_{1,c_1} \to M_{2,c_2}$$ that behaves as a restriction of $$f$$, this function is continuous.
This condition is equivalent to the one that you give, by the argument that you sketch.

**Comment by kbuzzard** [comment]
"a continuous inclusion between profinite spaces is a topological embedding".
